build_index_m:build_index_m.cpp ../build_index.cpp
	g++ -I /usr/local/berkeleydb/include/ -o build_index_m build_index_m.cpp ../build_index.cpp -L /usr/local/berkeleydb/lib/ -ldb -fno-stack-protector 
