search_server_v5_arrange:search_server_v5_arrange.cpp search.cpp
	g++ -I /usr/local/berkeleydb/include/ -o search_server_v5_arrange search_server_v5_arrange.cpp search.cpp -L /usr/local/berkeleydb/lib/ -ldb 
