build_index_oneword:build_index_oneword.cpp ../build_index.cpp
	g++ -I /usr/local/berkeleydb/include/ -o build_index_oneword build_index_oneword.cpp ../build_index.cpp -L /usr/local/berkeleydb/lib/ -ldb
